### ISSUE TITLE
Using LPD8806 on BeagleBone Black

### ISSUE THREAD

**Issue by ansrivas** [adammhaile/RPi-LPD8806#14]
Firstly thanks a lot for your awesome library.

I worked with raspberry pi and it worked like charm. But now I am trying to move to Beaglebone black.

As you mentioned, in the links, I compiled and enabled the device tree also. Now the issue is with the SPI interface.

After compilation of the overlay and exporting it, I get "/dev/spidev1.0" activated while the LPD8806 uses "/dev/spidev0.0" . 
So, I tried to change this in the LPD8806 library , recompiled , but unfortunately it doesn't work.

It will be very helpful if you can share some views over this.
## 

Thanks
Ankur

**Comment by adammhaile** [comment]
Unfortunately, the beagle bone black support was confirmed by someone else as I haven't had one until this week. But I have not had a chance to try it yet. Try installing py-spidev and set use_py_spi = True in the LEDStrip() constructor. It should work on any SPI device... have you read through the tutorials listed on the README?

**Comment by adammhaile** [comment]
Also, check the notes in this issue from the guy that got it to work: https://github.com/adammhaile/RPi-LPD8806/issues/9

**Comment by ansrivas** [comment]
Thanks for your reply, but even I got it up and working very nicely with your library.
I have shared a detailed process here on their forums.

http://forums.adafruit.com/viewtopic.php?f=49&t=53861

**Comment by adammhaile** [comment]
Awesome, thanks! I'll be sure to add all that setup info in the README soon :)
