### ISSUE TITLE
LPD8806 control failing on all fronts

### ISSUE THREAD

**Issue by domwrap** [adammhaile/RPi-LPD8806#20]
I don't believe this to be an issue specifically with your driver, however I am at a loss of where else to really ask so hoping for some know-how from others that have successfully built projects with the RPi and these LEDs.

Problem: I cannot get anything to correctly address and illuminate/alter the state of my LED strip.

I have a RasPi B and a Rasp B+ with 2A mUSB, hooked up to an LPD8806 LED strip, with separate 5A PSU, both 5V. I have re-done the GPIO connections ~~four~~ closer to ten times, with no change in result. I have decent experience with Linux, but somewhat beginner on the electronics side.

I have used a combination of
- Stock Raspbian
- Pre-installed Raspbian (From raspberry-at-home)
- Occidentalis from Adafruit
- RaspBMC, stock and preinstall (again from RAH)
- RasPlex

with tools
- Hyperion
- Ambi-TV
- https://github.com/Sh4d/LPD8806
- https://github.com/adammhaile/RPi-LPD8806
- Adafruit https://learn.adafruit.com/light-painting-with-raspberry-pi/software

I've enabled /etc/modules, I've removed blacklists, etc etc. The closest I've got is with Occidentalis and their own light-painting code. That does at least make the strip do _something_, even though it's not accurate.

I am eventually trying to build an Ambilight clone using Hyperion, and even my Fushicai grabber appears to be working which I thought that would be my biggest headache. If anybody has anything to save me from madness, I'd appreciate it. I came across your driver when I was looking for ways to debug my issues and try something other than Hyperion to address the LED strip,

Right now my (now cut to 50cm) strip/piece is all illuminated, though not all 100% white. None of the above tools seem to be affecting them at all.

Here's the result of spidev_test which tests positive on both Pi

``` code
$ sudo ./spidev_test -D /dev/spidev0.0
spi mode: 0
bits per word: 8
max speed: 500000 Hz (500 KHz)

FF FF FF FF FF FF 
40 00 00 00 00 95 
FF FF FF FF FF FF 
FF FF FF FF FF FF 
FF FF FF FF FF FF 
DE AD BE EF BA AD 
F0 0D
```

Here is an image of part of my strip, if it will make any difference

![LPD8806](https://lh6.googleusercontent.com/ULxtAGr2mnvC8go-irbBAWv3oelFyEZIajjzpyq64CZukIspz6IYGw=s600)

I'm repurposing an IDC connector (from an IDE ribbon cable) and have tested it again with my multimeter and I am using the correct pins. Re-ran all the tests but still get nothing.

Using the RPi B+ I have had more promising results in that _something_ happens (the B did basically nothing but the odd glimmer) but still not expected result. Here's a video running test scripts using both the LDP8806 and RPi-LPD8806 libraries.

The first couple are scripts I quickly wrote to turn all the LEDs red, second to individually set the 20th LED to red, and then the two included example scripts from each library.

https://www.youtube.com/watch?v=GEoaXNxi2Ds
_Noise warning at 1:04. That's my phone's low-battery alert, sorry._

I have since also run the RPi-LPD8806 off.py script which, as the name suggests, should turn all LEDs off. Similar to the video, the first two or three blink a couple times, then the strip resets itself to white.

Thank you a lot for any help.

**Comment by adammhaile** [comment]
Hate to say it but have you run it with a different LED strip? Yours could just be bad. Try bypassing the first chip (first two LEDs) and going for the second chip... maybe the first one is bad. Also, are you using a level shifter? Some strips (not all LPD8806 chips are the same) don't handle 3.3V well, or at all.

**Comment by domwrap** [comment]
Yeah I'd basically come to the same conclusion, save any revolutionary advice, that the strip might be bad. It's the only one I have right now, but I did just order another short-length from Adafruit to test and compare. Unfortunately I made that order yesterday with a bunch of other kit before I read in another post from you and again now about the level-shifter but, if the AF strip doesn't work either, I'll try that next. I'm shipping north of the border so hopefully small-item shipping isn't too much.

I've also not tried starting connection beyond the first LED on the strip as I don't have means of re-attaching connectors as I'm a UK expat with limited resources and the soldering iron I'll need is in the AF order. If their strip does work, that'll be my next move to try and save my 5m before I return it.

Thanks for the advice, I appreciate it. Only so much more hair I could tear out over this.

**Comment by domwrap** [comment]
I'm pretty embarrassed to admit this, but my elementary electronics shone through here: I was simply grounding the LED strip through the 5V mains supply, and was not also routing GND to the Pi. I learnt this through further frustration today when my Adafruit test strip arrived and I had the same issues on an Arduino and it seemed impossible to be coincidence. I triple checked the wiring diagram and realised my mistake. Sorry, and thanks for your help.

**Comment by adammhaile** [comment]
Ha... no worries. I've done it myself more than once. I'll need to remember
to put that tip in future documentation... :) Glad it's working!

**Comment by JosephAntony1** [comment]
I know this is awkward and 6 years later but I'm running into the same issue, the strip works when I try and run it on an Arduino, but I can't seem to get it to respond to anything from my pi :( 

To be more specific it used to work on my pi zero, but I can't get them running on my pi b
