### ISSUE TITLE
Please add a license and LICENSE file

### ISSUE THREAD

**Issue by Packetslave** [adammhaile/RPi-LPD8806#3]
Hi, could you please add a license to your project? Many companies (like mine) won't allow open-source contributions to projects without licenses. I have some patches I'd like to submit, but can't get them approved at the moment.

I personally recommend the Apache license, but it's obviously up to you.

**Comment by adammhaile** [comment]
License added. Out of curiosity, what's your company and what are you using the library for? I always love to see people's projects that use my code :)

**Comment by Packetslave** [comment]
Thanks! Might want to edit the LICENSE file to change "Copyright (c) [year] [fullname]"

I work for Google, although this is mostly a personal project. We have a 180-gallon aquarium with 3 turtles in our office (http://i.imgur.com/OvmC7D6.jpg). I'm planning to wrap a Pi-controlled LPD8806 strip around the base of the tank and use it along with a webcam and OpenCV to play Turtle Pong :-)

RIght now I just have it making pretty lights on the wall:  https://www.facebook.com/photo.php?v=10101093869179417&l=5901986977502568369

**Comment by adammhaile** [comment]
Cool! Looks awesome. would definitely love to see the finished project.
Fixed the license... thanks for pointing out my blatant copy/paste error :P

**Comment by adammhaile** [comment]
Just curious how the project was coming along. Would love to see it!
