### ISSUE TITLE
Thanks!  (and an example)

### ISSUE THREAD

**Issue by zzolo** [adammhaile/RPi-LPD8806#8]
Through many issues and frying a Raspberry Pi and LED strip (I am new at this stuff), I finally got my project done.

https://github.com/zzolo/lumiere

Its a web and text interface to change our holiday lighting on our house.  There's a video link in there to see an example.

I just wanted to say thanks for the great library which helped out a lot.

**Comment by adammhaile** [comment]
Very nice! I like what you did with it. Very slick interface. I'm actually working on a web interface to mine as well... though not NEARLY as pretty as yours :) https://github.com/adammhaile/LightPi-Web
Would you mind if I post about your project on my website? (ManiacalLabs.com)

**Comment by zzolo** [comment]
I assume yours is meant to run on the actual Raspberry Pi?  Mine is a bit different in that its deployed out in the internet and the Raspberry Pi polls the website which is a bit expensive but has some other benefits.

Yes, feel free to link away.
