### ISSUE TITLE
Adaption to Beaglebone

### ISSUE THREAD

**Issue by wprinz** [adammhaile/RPi-LPD8806#9]
Thanks for providing this useful code! I installed the code on a beaglebone and observed the following which might be usefull for other Beaglebone users.

If you follow the instructions on "http://elinux.org/BeagleBone_Black_Enable_SPIDEV" the resulting SPI0 device is /dev/spidev1.0 instead /dev/spidev0.0

Thus the code in bootstrap,py, LPD8806.py, and  ledstrip.py must be changed accordingly to reflect the different device name.

The Beaglebone pins that need to be connected to the LPD8806 strip are P9_22 for CLK and P9_18 for data, if you create the SPI0 mapping.

Furthermore make sure that you connect the ground of the Beaglebone and the Led strip power supply with each other. Otherwise you will receive a very erratic behaviour. I didn't recognise this and it cost me a 2 hours searching for the software bug ...

**Comment by adammhaile** [comment]
Thanks for the note! I'll get this integrated into the instructions soon!
